name: lint workflows

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint-workflows:
    uses: ${{ vars.SENZING_DEVSECOPS_ORG }}/build-resources/.github/workflows/lint-workflows.yaml@v1
